In [11]:
import glob
import random
import os
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import rasterio
from PIL import Image

import torch
from torch.utils.data import Dataset
from torchvision.utils import save_image
import torchvision.transforms as transforms

In [19]:

files_hr = '/home/ubuntu/PyTorch-GAN/data/img_hr_normalized/Tile_-2.08_41.29_EPSG4326_Gebco.tif'

img_hr = rasterio.open(files_hr)
img_hr = img_hr.read(1)
img_hr_png = np.around(img_hr*255)
img_hr_png_uint8=img_hr_png.astype(np.uint8)
img = Image.fromarray(img_hr_png_uint8)
img.save("images/save_a_png.png")



In [21]:
#Inverse max = 6362, min = -10956
max = 6362
min = -10956
img_open = Image.open("images/save_a_png.png")
img_open = np.float32(img_open)
print(img_open)
img_inverse = img_open/255
img_inverse_tif = img_inverse *(max-min)+min #MinMAx Normalization: img_hr_scl = (img_hr-min)/(max-min)

[[163. 163. 163. ... 152. 151. 151.]
 [163. 163. 163. ... 151. 151. 150.]
 [163. 163. 163. ... 151. 151. 150.]
 ...
 [161. 161. 161. ... 113. 113. 113.]
 [161. 161. 161. ... 113. 113. 113.]
 [161. 161. 161. ... 113. 113. 113.]]


In [24]:
#Verify
print(img_hr) #Normalized img with range [0,1]
print(img_inverse) # Inversed img read from PNG

img_hr_origin = rasterio.open('/home/ubuntu/PyTorch-GAN/data/img_hr_tif/Tile_-2.08_41.29_EPSG4326_Gebco.tif')
print(img_hr_origin.read(1)) # Original hr img
print(np.around(img_inverse_tif)) # Inversed img read from PNG




[[0.6390461  0.6389883  0.6389883  ... 0.59417945 0.59279364 0.59135   ]
 [0.6389883  0.6389883  0.6389883  ... 0.5929091  0.5915233  0.5901374 ]
 [0.6389883  0.6389306  0.6389306  ... 0.59163874 0.59031063 0.5889248 ]
 ...
 [0.63038456 0.6303268  0.6302691  ... 0.44260308 0.44242984 0.44254532]
 [0.6303268  0.6302691  0.6301536  ... 0.44242984 0.44231436 0.44231436]
 [0.6302691  0.63021135 0.63009584 ... 0.4424876  0.4424876  0.4420834 ]]
[[0.6392157  0.6392157  0.6392157  ... 0.59607846 0.5921569  0.5921569 ]
 [0.6392157  0.6392157  0.6392157  ... 0.5921569  0.5921569  0.5882353 ]
 [0.6392157  0.6392157  0.6392157  ... 0.5921569  0.5921569  0.5882353 ]
 ...
 [0.6313726  0.6313726  0.6313726  ... 0.44313726 0.44313726 0.44313726]
 [0.6313726  0.6313726  0.6313726  ... 0.44313726 0.44313726 0.44313726]
 [0.6313726  0.6313726  0.6313726  ... 0.44313726 0.44313726 0.44313726]]
[[  111   110   110 ...  -666  -690  -715]
 [  110   110   110 ...  -688  -712  -736]
 [  110   109   109 ...  -

In [ ]:
# Take reciprocol

In [38]:
files_hr = '/home/ubuntu/PyTorch-GAN/data/img_lr_reci/Tile_-2.08_41.29_EPSG4326_Etopo.tif'

img_hr = rasterio.open(files_hr)
img_hr = img_hr.read(1)
img_hr_png = np.around(img_hr*255)
img_hr_png_uint8=img_hr_png.astype(np.uint8)
img = Image.fromarray(img_hr_png_uint8)
img.save("images/save_reci_png.png")

In [39]:
#Inverse max = 10.0, min = -1.1111111640930176-1.000001072883606

max = 1000000.0
min = -1.000001072883606
offset = 1e-6
img_open = Image.open("images/save_reci_png.png")
img_open = np.float32(img_open)
img_inverse = img_open/255
img_inverse_tif = 1/(np.square(img_inverse)*(max-min)+min) - offset #MinMAx Normalization: img_hr_scl = (img_hr-min)/(max-min)

In [40]:
#Verify
print(img_hr) #Normalized img with range [0,1]
print(img_inverse) # Inversed img read from PNG

img_hr_origin = rasterio.open('/home/ubuntu/PyTorch-GAN/data/img_hr_tif/Tile_-2.08_41.29_EPSG4326_Gebco.tif')
print(img_hr_origin.read(1)) # Original hr img
print(np.around(img_inverse_tif)) # Inversed img read from PNG

[[0.00100462 0.00100504 0.00100542 ... 0.0009993  0.00099939 0.00099944]
 [0.00100471 0.00100471 0.00100514 ... 0.00099935 0.00099942 0.00099947]
 [0.00100499 0.00100475 0.00100475 ... 0.00099939 0.00099945 0.00099949]
 ...
 [0.00098974 0.00099087 0.00099293 ... 0.00099985 0.00099985 0.00099985]
 [0.00098675 0.00099087 0.00099424 ... 0.00099985 0.00099985 0.00099985]
 [0.00098561 0.00099103 0.00099494 ... 0.00099985 0.00099985 0.00099985]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[  111   110   110 ...  -666  -690  -715]
 [  110   110   110 ...  -688  -712  -736]
 [  110   109   109 ...  -710  -733  -757]
 ...
 [  -39   -40   -41 ... -3291 -3294 -3292]
 [  -40   -41   -43 ... -3294 -3296 -3296]
 [  -41   -42   -44 ... -3293 -3293 -3300]]
[[-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -